[package]
name = variable::get("crate_name")
description = "AstragoDE's Rust Template"
version = "0.1.0"
edition = "2021"
authors = ["AstragoDE <51675359+AstragoDE@users.noreply.github.com>"]
readme = "README.md"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.19"
pretty_env_logger = "0.5.0"
